const menu = [
  {
    name: "Pepperoni Pizza Slice",
    type: "Main course",
    ingredients: "Dough, Cheese, Pepperoni",
    vegetarian: false,
    price: 2.0,
    img: "http",
    instock: true,
  },
  {
    name: "Whole Pepperoni Pizza",
    type: "Main course",
    ingredients: "Dough, Cheese, Pepperoni",
    vegetarian: false,
    price: 10.5,
    img: "http",
    instock: true,
  },
  {
    name: "Burger",
    type: "Main course",
    ingredients: "Bun, Cheese, Tomato, Onion, Ground-beef",
    vegetarian: false,
    price: 8.0,
    img: "http",
    instock: true,
  },
  {
    name: "Vegan Burger",
    type: "Main course",
    ingredients: "Bun, Cheese, Tomato, Onion, Bean, Soybean, Tofu",
    vegetarian: true,
    price: 8.5,
    img: "http",
    instock: true,
  },
  {
    name: "Grilled Ribeye Steak",
    type: "Main course",
    ingredients: "Meat from beef rib, Butter, Sauteed onions, Sauteed garlic",
    vegetarian: false,
    price: 30.0,
    img: "http",
    instock: true,
  },
  {
    name: "Grilled Pork Chop",
    type: "Main course",
    ingredients: "Meat from loin, Butter, Sauteed onions, Sauteed garlic",
    vegetarian: false,
    price: 15.0,
    img: "http",
    instock: true,
  },
  {
    name: "French Fries",
    type: "Side dish",
    ingredients: "Potato, Vegetable Oil, Salt",
    vegetarian: true,
    price: 7.0,
    img: "http",
    instock: true,
  },
  {
    name: "Chicken Wing",
    type: "Side dish",
    ingredients: "Chicken Wing, Garlic, Pepper, Salt",
    vegetarian: false,
    price: 7.0,
    img: "http",
    instock: true,
  },
  {
    name: "Buffalo Chicken Wing",
    type: "Side dish",
    ingredients:
      "Chicken Wing, Garlic, Pepper, Salt, Flour, Melted-butter, Vinigar, Hot-sauce",
    vegetarian: false,
    price: 7.0,
    img: "http",
    instock: true,
  },
  {
    name: "Mashed Potato",
    type: "Side dish",
    ingredients: "Potato, Butter, cream, milk, Salt.",
    vegetarian: false,
    price: 7.0,
    img: "http",
    instock: true,
  },
  {
    name: "Salad Caprese",
    type: "Side dish",
    ingredients:
      "Sliced mozzarella, Sliced tomatoes, Sweet basil, Olive oil, Salt.",
    vegetarian: true,
    price: 7.0,
    img: "http",
    instock: true,
  },
    type: "dessert",
    ingredients: "Apple, Flour, Milk, Sugar, Cinnamon, Butter, Salt",
    vegetarian: false,
    price: 7.0,
    img: "http",
    instock: true,
  },
  {
    name: "ice cream",
    type: "Side dish",
    ingredients: "Milk, Sugar",
    vegetarian: false,
    price: 7.0,
    img: "http",
    instock: true,
  },
];
