const menu = [
  {
    name: "Pepperoni Pizza Slice",
    type: "Main course",
    vegetarian: false,
    price: 2.0,
    img: "http",
    instock: true,
  },
  {
    name: "Whole Pepperoni Pizza",
    type: "Main course",
    vegetarian: false,
    price: 10.5,
    img: "http",
    instock: true,
  },
  {
    name: "Burger",
    type: "Main course",
    vegetarian: false,
    price: 8.0,
    img: "https://images.immediate.co.uk/production/volatile/sites/2/2015/04/2015-02-24-olive-test-d5b505c.jpg?quality=90&crop=7px,1865px,3278px,1410px&resize=556,505",
    instock: false,
  },
  {
    name: "Vegan Burger",
    type: "Main course",
    vegetarian: true,
    price: 8.5,
    img: "http",
    instock: true,
  },
  {
    name: "Grilled Ribeye Steak",
    type: "Main course",
    vegetarian: false,
    price: 30.0,
    img: "http",
    instock: true,
  },
  {
    name: "Grilled Pork Chop",
    type: "Main course",
    vegetarian: false,
    price: 15.0,
    img: "http",
    instock: true,
  },
  {
    name: "French Fries",
    type: "Side dish",
    vegetarian: true,
    price: 7.0,
    img: "http",
    instock: true,
  },
  {
    name: "Chicken Wing",
    type: "Side dish",
    vegetarian: false,
    price: 10.5,
    img: "http",
    instock: true,
  },
  {
    name: "Buffalo Chicken Wing",
    type: "Side dish",
    vegetarian: false,
    price: 11.0,
    img: "http",
    instock: true,
  },
  {
    name: "Mashed Potato",
    type: "Side dish",
    price: 7.0,
    img: "http",
    instock: false,
  },
  {
    name: "Salad Caprese",
    type: "Side dish",
    vegetarian: true,
    price: 7.5,
    img: "http",
    instock: true,
  },
  {
    name: "Slice of Apple Pie",
    type: "dessert",
    vegetarian: false,
    price: 8.0,
    img: "http",
    instock: true,
  },
  {
    name: "3 Different Ice Cream Scoops",
    type: "Side dish",
    vegetarian: false,
    price: 10.0,
    img: "http",
    instock: true,
  },
];

export { menu };
