const menu = [
  {
    name: "Pepperoni Pizza Slice",
    type: "Main course",
    vegetarian: false,
    price: 2.0,
    img: "",
    instock: true,
  },
  {
    name: "Whole Pepperoni Pizza",
    type: "Main course",
    vegetarian: false,
    price: 10.5,
    img: "whole pizza.jpg",
    instock: true,
  },
  {
    name: "Burger",
    type: "Main course",
    vegetarian: false,
    price: 8.0,
    img: "burger.jpg",
    instock: false,
  },
  {
    name: "Vegan Burger",
    type: "Main course",
    vegetarian: true,
    price: 8.5,
    img: "",
    instock: true,
  },
  {
    name: "Grilled Ribeye Steak",
    type: "Main course",
    vegetarian: false,
    price: 30.0,
    img: "",
    instock: true,
  },
  {
    name: "Grilled Pork Chop",
    type: "Main course",
    vegetarian: false,
    price: 15.0,
    img: "",
    instock: true,
  },
  {
    name: "French Fries",
    type: "Side dish",
    vegetarian: true,
    price: 7.0,
    img: "",
    instock: true,
  },
  {
    name: "Chicken Wing",
    type: "Side dish",
    vegetarian: false,
    price: 10.5,
    img: "",
    instock: true,
  },
  {
    name: "Buffalo Chicken Wing",
    type: "Side dish",
    vegetarian: false,
    price: 11.0,
    img: "",
    instock: true,
  },
  {
    name: "Mashed Potato",
    type: "Side dish",
    price: 7.0,
    img: "",
    instock: false,
  },
  {
    name: "Salad Caprese",
    type: "Side dish",
    vegetarian: true,
    price: 7.5,
    img: "",
    instock: true,
  },
  {
    name: "Slice of Apple Pie",
    type: "dessert",
    vegetarian: false,
    price: 8.0,
    img: "",
    instock: true,
  },
  {
    name: "3 Different Ice Cream Scoops",
    type: "Side dish",
    vegetarian: false,
    price: 10.0,
    img: "",
    instock: true,
  },
];

export { menu };
